### ISSUE TITLE
value值绑定对象时报错

### ISSUE THREAD

**Issue by caroundsky** [bartlian/el-virtual-select#2]
![Snipaste_2022-11-12_15-51-03](https://user-images.githubusercontent.com/20423068/201464541-4155ec03-6562-4709-9bea-5cdc78c9155d.png)

**Comment by bartlian** [comment]
options 属性 传递的数组，数组项里面的对象属性默认取的键值是label, value，如果满足这个就不用传value-key, label-key。value-key, label-key 只是用来覆盖键值的，比如
`const targetPortsList = [{code: 'ADALV', city: '安道尔'}]` 这种情况下，需要传`label-key="city"  value-key="code"`

**Comment by caroundsky** [comment]
> options 属性 传递的数组，数组项里面的对象属性默认取的键值是label, value，如果满足这个就不用传value-key, label-key。value-key, label-key 只是用来覆盖键值的，比如 `const targetPortsList = [{code: 'ADALV', city: '安道尔'}]` 这种情况下，需要传`label-key="city" value-key="code"`

键名映射是没问题，其实期望的是v-model能绑定对象

**Comment by bartlian** [comment]
> > options 属性 传递的数组，数组项里面的对象属性默认取的键值是label, value，如果满足这个就不用传value-key, label-key。value-key, label-key 只是用来覆盖键值的，比如 `const targetPortsList = [{code: 'ADALV', city: '安道尔'}]` 这种情况下，需要传`label-key="city" value-key="code"`
> 
> 键名映射是没问题，其实期望的是v-model能绑定对象

这个不支持。这种情况，想获取整个项，可以监听change事件，`(val) => {const target = list.find(i => i.code === val)}`,这样来拿到选中的项

**Comment by caroundsky** [comment]
> > > options 属性 传递的数组，数组项里面的对象属性默认取的键值是label, value，如果满足这个就不用传value-key, label-key。value-key, label-key 只是用来覆盖键值的，比如 `const targetPortsList = [{code: 'ADALV', city: '安道尔'}]` 这种情况下，需要传`label-key="city" value-key="code"`
> > 
> > 
> > 键名映射是没问题，其实期望的是v-model能绑定对象
> 
> 这个不支持。这种情况，想获取整个项，可以监听change事件，`(val) => {const target = list.find(i => i.code === val)}`,这样来拿到选中的项

好的，谢谢

**Comment by bartlian** [comment]
> > > > options 属性 传递的数组，数组项里面的对象属性默认取的键值是label, value，如果满足这个就不用传value-key, label-key。value-key, label-key 只是用来覆盖键值的，比如 `const targetPortsList = [{code: 'ADALV', city: '安道尔'}]` 这种情况下，需要传`label-key="city" value-key="code"`
> > > 
> > > 
> > > 键名映射是没问题，其实期望的是v-model能绑定对象
> > 
> > 
> > 这个不支持。这种情况，想获取整个项，可以监听change事件，`(val) => {const target = list.find(i => i.code === val)}`,这样来拿到选中的项
> 
> 好的，谢谢

没事
