### ISSUE TITLE
无法绑定初始值

### ISSUE THREAD

**Issue by proso** [bartlian/el-virtual-select#3]
当初始值在下拉列表的位置超出默认的第一页时，无法正常显示绑定值的label，只会显示value

**Comment by bartlian** [comment]
可以安装最新版本0.10.0，前几天公司项目有个详情匹配的场景，也遇到这个问题了，现在已修复了。不过需要注意的是，只有在组件mounted或者options从无值到有值时，会触发匹配label(主要是解决详情展示问题)。像我同事，在一个模态框里，关闭之后，没销毁模态框组件，再次用同样的数据打开模态框，没触发匹配label，所以像这种情况，可以打开的时候再重新渲染这个下拉组件，让触发匹配label。

**Comment by bartlian** [comment]
> 当初始值在下拉列表的位置超出默认的第一页时，无法正常显示绑定值的label，只会显示value

可以安装最新版本0.10.0，前几天公司项目有个详情匹配的场景，也遇到这个问题了，现在已修复了。不过需要注意的是，只有在组件mounted或者options从无值到有值时，会触发匹配label(主要是解决详情展示问题)。像我同事，在一个模态框里，关闭之后，没销毁模态框组件，再次用同样的数据打开模态框，没触发匹配label，所以像这种情况，可以打开的时候再重新渲染这个下拉组件，让触发匹配label。

**Comment by JohnnyZhang0628** [comment]
![image](https://github.com/bartlian/el-virtual-select/assets/28375774/74bb7ed1-8762-4853-8da7-b4e46009793e)
多选的时候，回显只能显示第一个靠前的选项，测试了好几遍都是这样。 @bartlian 你看下

**Comment by bartlian** [comment]
> 

感谢反馈。已修复，下载最新版本，看看

**Comment by bartlian** [comment]
> ![image](https://user-images.githubusercontent.com/28375774/246708633-74bb7ed1-8762-4853-8da7-b4e46009793e.png) 多选的时候，回显只能显示第一个靠前的选项，测试了好几遍都是这样。 @bartlian 你看下

感谢反馈。已修复，下载最新版本，看看

**Comment by JohnnyZhang0628** [comment]
还有一个小问题，就是多选选中一个选项后，会默认回到第一个选项，这个好像element 的问题
